[tool.black]
line-length = 99

[tool.isort]
line_length = 99
profile = "black"

[tool.flake8]
max-line-length = 99
max-complexity = 18
show-source = true
ignore = [
  "E501",   # Line too long.
  "PIE786", # Use precise exception handlers.
  "PIE803", # Use lazy % formatting in logging functions.
  "W503",   # Line break occurred before a binary operator.
]

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.*"]
allow_untyped_defs = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = [
  "B404", # Importing subprocess
  "B603", # Calling subprocess.Popen without shell=True
]
