[tool.black]
line-length = 88

[tool.isort]
line_length = 88
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.*"]
allow_untyped_defs = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = [
  "B404", # Importing subprocess
  "B603", # Calling subprocess.Popen without shell=True
]
