name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.11"
  LD_LIBRARY_PATH: /usr/local/lib
  GCC_VERSION: "12"
  # renovate: datasource=pypi depName=vapoursynth
  VAPOURSYNTH_VERSION: "62"

jobs:
  ci:
    name: CI
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
        vapoursynth-version: ["${{ env.VAPOURSYNTH_VERSION }}"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install vapoursynth make-deps
        run: |
          sudo apt update
          sudo apt install cython3 libzimg-dev meson ninja-build g++-${{ env.GCC_VERSION }}

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-R${{ matrix.vapoursynth-version }}-${{ env.GCC_VERSION }}

      - name: Configure shell
        run: echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV

      - name: Install vapoursynth
        run: |
          git clone https://github.com/vapoursynth/vapoursynth --depth 1 -b R${{ matrix.vapoursynth-version }}
          pushd vapoursynth
          ./autogen.sh
          ./configure --disable-x86-asm --disable-vspipe
          make -j2
          sudo make install -j2
          popd
          rm -rf vapoursynth

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Check code quality
        run: poetry run poe ci

  publish-pypi:
    name: Build and release to PyPI
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning[plugin]

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
