name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.11"
  LD_LIBRARY_PATH: /usr/local/lib
  # renovate: datasource=pypi depName=vapoursynth
  VAPOURSYNTH_VERSION: "62"

jobs:
  ci:
    name: CI
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install vapoursynth
        uses: deadnews/setup-vapoursynth@main

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Check code quality
        run: poetry run poe ci

      - name: Check vapoursynth
        run: poetry run python -c "import vapoursynth; print(vapoursynth.core.version_number())"

  publish-pypi:
    name: Build and release to PyPI
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning[plugin]

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
